services:
  technopoly:
    image: gonzalomg0/technopoly:latest
    container_name: technopoly
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data
    env_file:
      - .env